### ISSUE TITLE
Deployment doesn't work

### ISSUE THREAD

**Issue by sergeyzwezdin** [Goodsmileduck/yandex-serverless-action#1]
Trying to setup YF deployment. Here is how my workflow definition looks:

![CleanShot 2019-11-25 at 05 23 52@2x](https://user-images.githubusercontent.com/800755/69504369-ed7f7480-0f43-11ea-94e8-2731cf2932af.png)

But when I run it, I'm getting an error:

<img width="904" alt="CleanShot 2019-11-25 at 05 24 47@2x" src="https://user-images.githubusercontent.com/800755/69504375-f2dcbf00-0f43-11ea-99ef-71dcb7832a64.png">

**Comment by Goodsmileduck** [comment]
Thanks for reaching out, will check it today!

**Comment by Goodsmileduck** [comment]
@sergeyzwezdin can you check logs in build stage which version of `yc` you got installed?
line should looks like:
```
Yandex.Cloud CLI 0.41.1 linux/amd64
```

**Comment by Goodsmileduck** [comment]
btw, it's probably I didn't make it clear, you need to create function in console, before running pipeline. So please check you already have a function with name `index.handler` in yandex cloud

**Comment by Goodsmileduck** [comment]
I missed pointing that you need to set env `ENTRYPOINT` 
check it here https://github.com/Goodsmileduck/example-yandex-serverless-action/blob/master/.github/workflows/main.yml
just tested without settings `ENTRYPOINT` got same error. 

README.md updated
drop a comment here once you got it fixed.

**Comment by sergeyzwezdin** [comment]
@Goodsmileduck I added `ENTRYPOINT`. The error is gone, but now I have another one:

> ERROR: failed to find function with name "test123": iam token create failed: rpc error: code = Unauthenticated desc = OAuth token is invalid or expired

Does it mean that I need IAM token instead of API token in Yandex Cloud?
If so, I have public and private key - where to place both of them?

**Comment by Goodsmileduck** [comment]
Since it's yc in docker container you need to set TOKEN with token for yc
check Initialization step 1
https://cloud.yandex.com/docs/cli/quickstart

**Comment by Goodsmileduck** [comment]
Сurrent state of action is kind of workaround to make deployment pipeline, I hope to check api of functions to write more native pipeline action.

**Comment by sergeyzwezdin** [comment]
Understood. Yes, with user token it works.
Hope it will support service accounts in the future.
Thank you for assistance!
