### ISSUE TITLE
Feature request: add service account option

### ISSUE THREAD

**Issue by avidale** [Goodsmileduck/yandex-serverless-action#12]
**The requested feature**: add parameter `service-account-id` to the action.

Generally, it is expected that all the parameters described by  `yc serverless function version create --help` can be passed to the action.

**Why it is important**: when a [service account](https://cloud.yandex.ru/docs/iam/quickstart-sa) is added to a function, it can receive [IAM-tokens](https://cloud.yandex.ru/docs/functions/operations/function-sa) on each call and use them to call other APIs of Yandex.Cloud (e.g. translate API). This is very convenient e.g. for Alice skills using these APIs.

**Comment by Goodsmileduck** [comment]
@avidale just added 2 parameters:
```
service_account: service-account-id
description: function description
```

tags will add in the next updates
