### ISSUE TITLE
Error if environment not passed

### ISSUE THREAD

**Issue by NekitCorp** [Goodsmileduck/yandex-serverless-action#19]
In [configuration](https://github.com/Goodsmileduck/yandex-serverless-action#configuration) section indicated that the parameter  `environment` not required. But if it is not passed, then there will be an error:

```
##[error]3 INVALID_ARGUMENT: Validation failed:
  - environment[]: Field does not match the pattern /[a-zA-Z][a-zA-Z0-9_]*/
```

**Comment by Goodsmileduck** [comment]
Should be fixed already
