### ISSUE TITLE
ERROR: zip archive content exceeds the maximum size 3.5 MB, use object storage to upload the content

### ISSUE THREAD

**Issue by opiumfor** [Goodsmileduck/yandex-serverless-action#5]
https://github.com/Goodsmileduck/yandex-serverless-action/blob/22f7f175f5cea0fd33f33dc3e31581a1adc0a2b8/entrypoint.sh#L53

Hi!

Function version uploaded into the cloud storage is being afterwards "created" with --source-path, which is wrong. Instead it should be created with --package-bucket-name and --package-object-name.

Would you be able to fix it? For my part, I could offer to make a pull request.

Thank you for such a great tool!

**Comment by Goodsmileduck** [comment]
@opiumfor thanks for catch. It's my fault, after update just copy-pasted lines. Check with master branch now. Commend if it was fixed

**Comment by opiumfor** [comment]
Yes, it works now! Thank you very much!
