### ISSUE TITLE
The action doesn't cleanup after deployment

### ISSUE THREAD

**Issue by sergeyzwezdin** [Goodsmileduck/yandex-serverless-action#7]
If I deploy more than one YF in a single GH workflow, files from the first deployed function appear in second function. Probably need to clean up `SOURCE_DIR` before zipping/deployment.

**Comment by Goodsmileduck** [comment]
Have you tried to use new job instead of new step for that? Between steps workspace is shared

**Comment by sergeyzwezdin** [comment]
Yes another job will be run in a separate environment and it will definitely work.
But I intentionally want to deploy it in the same job. Probably it needs to cleanup source dir for docker container.

**Comment by Goodsmileduck** [comment]
@sergeyzwezdin looks like problem that zip command append files to archive.
I added `rm -f` command in end, check now from master please

**Comment by sergeyzwezdin** [comment]
@Goodsmileduck yep, that's work! thank you!
